<?php
/**
 * PartnerEmailSendApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Splashifypro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Splashify Pro API
 *
 * REST endpoints for two product surfaces: 1. **Public API** under /public/_* — WhatsApp messaging, contacts, conversations, transactional email, Meta Conversions API. Authenticate with sk_live_… keys. 2. **Partner Email API** under /partner/email/_* — AWS-SES-shaped resold email platform: identities, configuration sets, templates, suppression, send, send-template, send-bulk, send-raw, quotas, stats, reputation, events. Authenticate with pk_live_… keys. SDKs for Node.js, Python, and PHP are auto-generated from this spec.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@splashifypro.in
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.22.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Splashifypro\Test\Api;

use \Splashifypro\Configuration;
use \Splashifypro\ApiException;
use \Splashifypro\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PartnerEmailSendApiTest Class Doc Comment
 *
 * @category Class
 * @package  Splashifypro
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PartnerEmailSendApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for partnerEmailEmailsMessageIdGet
     *
     * Get email status.
     *
     */
    public function testPartnerEmailEmailsMessageIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnerEmailSendBulkPost
     *
     * Send bulk templated email.
     *
     */
    public function testPartnerEmailSendBulkPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnerEmailSendPost
     *
     * Send email.
     *
     */
    public function testPartnerEmailSendPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnerEmailSendRawPost
     *
     * Send raw MIME email.
     *
     */
    public function testPartnerEmailSendRawPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for partnerEmailSendTemplatePost
     *
     * Send templated email.
     *
     */
    public function testPartnerEmailSendTemplatePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
